name: .NET Core

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.300
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal


        #deploy
        #only if push
      - name: Publish
        if: ${{ github.event_name=='push'}}
        run: dotnet publish --configuration Release --framework netcoreapp3.1 -p:PublishSingleFile=false -p:PublishTrimmed=true --runtime linux-x64 --self-contained true
      - name: Set RealeaseType master
        if: ${{ github.ref=='refs/heads/master' && github.event_name=='push'}}
        run: echo ::set-env name=REALEASE_TYPE::$(echo "public/")
      - name: Set RealeaseType dev
        if: ${{ github.ref=='refs/heads/dev' && github.event_name=='push'}}
        run: echo ::set-env name=REALEASE_TYPE::$(echo "beta/")
      - name: Deploy to Server
        if: ${{ github.event_name=='push'}}
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_SERVER_KEY }}
          SOURCE: "/Kudos/bin/Release/netcoreapp3.1/linux-x64/publish"
          REMOTE_HOST: ${{ secrets.SSH_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.SSH_REMOTE_USER }}
          TARGET: "${{ secrets.SSH_REMOTE_TARGET }}${{ env.REALEASE_TYPE }}"
      - name: Start new Version
        if: ${{ github.event_name=='push'}}
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.SSH_REMOTE_HOST }}
          username: ${{ secrets.SSH_REMOTE_USER }}
          privateKey: ${{ secrets.SSH_SERVER_KEY}}
          command: |
            cd Kudos/${{ env.REALEASE_TYPE }}publish
            pid=$(cat 'last.pid')
            kill $pid
            nohup ./Kudos >/dev/null 2>&1 &
            echo "$!" > last.pid
            ~.
