name: .NET Core

on:
  push:
    branches: [ master , dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    
   

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release --framework netcoreapp3.1 -p:PublishSingleFile=false -p:PublishTrimmed=true --runtime linux-x64 --self-contained true
    
      #deploy
      #only if push
      
    - name: Extract Branch Name
      if: ${{ github.event_name=='push'}}
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF##*/})"
    - name: Set RealeaseType
      if: ${{ github.event_name=='push'}}
      run: |
         if ["$BRANCH_NAME" == master]; then
            set-env name=REALEASE_TYPE::$(echo "public")
          else 
            set-env name=REALEASE_TYPE::$(echo "beta")
         fi
    - name: Deploy to Server
      if: ${{ github.event_name=='push'}}
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
         SSH_PRIVATE_KEY: ${{ secrets.SSH_SERVER_KEY }}
         SOURCE: "/Kudos/bin/Release/netcoreapp3.1/linux-x64/${{ env.REALEASE_TYPE }}"
         REMOTE_HOST: ${{ secrets.SSH_REMOTE_HOST }}
         REMOTE_USER: ${{ secrets.SSH_REMOTE_USER }}
         TARGET: ${{ secrets.SSH_REMOTE_TARGET }}
    - name: Run a command remotely
      if: ${{ github.event_name=='push'}}
      uses: docker://evaneos/ssh-action:0.1.0
      with:
        hosts: ${{ secrets.SSH_REMOTE_HOST }}
        user: ${{ secrets.SSH_REMOTE_USER }}
        private_key: ${{ secrets.SSH_SERVER_KEY }}
        commands: |
          cd Kudos/${{ env.REALEASE_TYPE }}
          pid=$(cat pid)
          kill $pid
          nohup ./Kudos &
          echo $! > pid