name: .NET Core

on:
  push:
    branches: [ master , dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release --framework netcoreapp3.1 --output target\ -p:PublishSingleFile=false -p:PublishTrimmed=true --runtime linux-x64 --self-contained true
   
   #deploy
  #  - name: Install Node.js
  #    uses: actions/setup-node@v1
  #    with:
  #      node-version: '10.x'
  #  - name: Install npm dependencies
  #    run: npm install
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_SERVER_KEY }}
          SOURCE: "/home/runner/work/kudos/kudos/target/"
          REMOTE_HOST: ${{ secrets.SSH_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.SSH_REMOTE_USER }}
          TARGET: ${{ secrets.SSH_REMOTE_TARGET }}