name: Version Check

on:
  pull_request:
    branches: [master , dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: echo tree
        run: |
          find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
      - name: Execute JavaScript inline
        uses: satackey/action-js-inline@v0.0.2
        with:
          required-packages: child_process
          script: |
            const ChildProcess = require("child_process");
            const core = require('@actions/core')
            const exec = require('@actions/exec');
            await exec.exec('.github/workflows/version-check.js');

