name: Version Check

on:
  pull_request:
    branches: [master , dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        run: |
          git clone https://github.com/TheBlue-1/kudos.git ./
          git checkout ${{ github.base_ref }}
          git checkout ${{ github.head_ref }}
      - name: Execute JavaScript inline
        uses: satackey/action-js-inline@v0.0.2
        with:
          required-packages: child_process simple-git
          script: |
            const ChildProcess = require("child_process");
            const core = require('@actions/core')
            main();
            function main(){
            if(!isVersionChanged())
            core.setFailed(`Version must be changed!`)
            }
            function isVersionChanged(){
            let changes=ChildProcess.execSync("git diff ${{ github.base_ref }} ${{ github.head_ref }} -- Kudos/Kudos.csproj", { encoding: "utf8" })
            let regex= /[-+]\s*<Version>(.*?)<\/Version>/g
            let matches =changes.matchAll(regex);
            if(matches==null) return false;
            let versions= [... matches]
            if(versions.length<2||versions[0][1]==versions[1][1])
            return false;
            
            return true;
            }
