name: Version Check

on:
  pull_request:
    branches: [master , dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        run: git clone https://github.com/TheBlue-1/kudos.git ./
      - name: test
        run: git diff HEAD master -- Kudos/Kudos.csproj
      - name: Execute JavaScript inline
        uses: satackey/action-js-inline@v0.0.2
        with:
          required-packages: child_process simple-git
          script: |
            const ChildProcess = require("child_process");
            const core = require('@actions/core')
            main();
            function main(){
            if(!isVersionChanged())
            core.setFailed(`Version must be changed!`)
            }
            function isVersionChanged(){
            let changes=ChildProcess.execSync("git diff HEAD master -- Kudos/Kudos.csproj", { encoding: "utf8" })
            console.error("changes:\n" + changes);
            return true;
            }
