name: Version Check

on:
  pull_request:
    branches: [master , dev]
    #dev for testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Execute JavaScript inline
        uses: satackey/action-js-inline@v0.0.2
        with:
          required-packages: child_process
          script: |
            const exec = require('@actions/exec');
            await exec.exec('node','.github/workflows/version-check.js');

